import os
import json

class CodeGenerator:
    def __init__(self, output_dir="."):
        self.output_dir = output_dir

    def generate(self, arch: dict):
        project_name = arch.get("project_name", "GeneratedApp")
        entities = arch.get("entities", [])
        relations = arch.get("relations", [])
        routes = arch.get("routes", [])
        has_auth = arch.get("auth", False)
        
        main_path = os.path.join(self.output_dir, "main.aayu")
        
        lines = []
        lines.append(f"# {project_name} - Generated by AAYU Intent-to-Application Platform")
        lines.append("use http.")
        lines.append("use db.")
        
        if has_auth:
            lines.append("use auth.")
            
        lines.append("")
        
        # Build relational fields map
        foreign_keys = {e: [] for e in entities}
        for rel in relations:
            if rel["type"] == "1:N":
                if rel["to"] in foreign_keys:
                    foreign_keys[rel["to"]].append(f"{rel['from'].lower()}_id")
            elif rel["type"] == "M:N":
                junc = rel["junction"]
                if junc in foreign_keys:
                    foreign_keys[junc].append(f"{rel['from'].lower()}_id")
                    foreign_keys[junc].append(f"{rel['to'].lower()}_id")
        
        # 1. Generate Database Models
        lines.append("# --- Database Models ---")
        if entities:
            for ent in entities:
                lines.append(f"entity {ent}.")
                lines.append("    text name.")
                lines.append("    text created_at.")
                
                for fk in foreign_keys.get(ent, []):
                    lines.append(f"    number {fk}.")
                    
                lines.append("end.")
                lines.append("")
                
        # 2. CRUD Auto-Generation (Intent Engine v4)
        lines.append("# --- CRUD Generation ---")
        for ent in entities:
            if ent in ["Role", "Permission", "UserRole", "User", "Account"]: continue
            lines.append(f"crud {ent}.")
            lines.append("")
                
        # 3. Generate Web Routes (Backend)
        lines.append("# --- Backend Routes ---")
        for route in routes:
            route_name = route.strip("/").replace("/", "_").title()
            if not route_name:
                route_name = "Home"
            func_name = f"handle_{route_name.lower()}"
                
            lines.append(f"task {func_name} with req.")
            lines.append(f"    return render \"{route_name}.html\".")
            lines.append("end.")
            lines.append(f"route \"{route}\" to {func_name}.")
            lines.append("")
            
        lines.append("serve on 8080.")
        
        with open(main_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python -m intent_engine.code_generator <architecture.json>")
        sys.exit(1)
        
    arch_file = sys.argv[1]
    with open(arch_file, "r") as f:
        arch = json.load(f)
        
    generator = CodeGenerator()
    generator.generate(arch)
    print("AAYU project generated successfully with Intent-to-Silicon pipeline!")

