import os
import json

class CodeGenerator:
    def __init__(self, output_dir="."):
        self.output_dir = output_dir

    def get_template_content(self, project_name, route_name, entities, has_auth):
        """Generates domain-specific aesthetic UI templates."""
        
        # Base CSS for modern look
        css = """
        <style>
            :root { --primary: #4f46e5; --bg: #f9fafb; --text: #111827; --card: #ffffff; --border: #e5e7eb; }
            body { font-family: 'Inter', system-ui, sans-serif; background-color: var(--bg); color: var(--text); margin: 0; padding: 0; }
            header { background-color: var(--primary); color: white; padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; }
            header h1 { margin: 0; font-size: 1.5rem; }
            nav a { color: white; text-decoration: none; margin-left: 1rem; font-weight: 500; }
            .container { max-width: 1200px; margin: 2rem auto; padding: 0 1rem; }
            .card { background: var(--card); border: 1px solid var(--border); border-radius: 0.5rem; padding: 1.5rem; margin-bottom: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .card h2 { margin-top: 0; color: var(--primary); }
            table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
            th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
            th { background-color: #f3f4f6; font-weight: 600; }
            .btn { display: inline-block; background: var(--primary); color: white; padding: 0.5rem 1rem; border-radius: 0.25rem; text-decoration: none; border: none; cursor: pointer; }
            .btn:hover { opacity: 0.9; }
        </style>
        """

        nav_links = ""
        if has_auth and route_name != "login":
            nav_links += "<a href='/login'>Login</a>"
        nav_links += f"<a href='/'>Home</a>"

        header = f"""
        <header>
            <h1>{project_name}</h1>
            <nav>{nav_links}</nav>
        </header>
        """

        content = ""
        if route_name in ["dashboard", "home", "index"]:
            content = f"<div class='card'><h2>Welcome to {project_name}</h2><p>This is your {route_name.title()}.</p></div>"
            
            # Generate mock tables for each entity
            for ent in entities:
                if ent in ["Role", "Permission", "UserRole", "User", "Account"]: continue # skip auth internals in dashboard
                content += f"""
                <div class='card'>
                    <h3>Recent {ent}s</h3>
                    <table>
                        <thead><tr><th>ID</th><th>Name</th><th>Created At</th><th>Actions</th></tr></thead>
                        <tbody>
                            <tr><td>1</td><td>Sample {ent}</td><td>2026-01-01</td><td><button class='btn'>View</button></td></tr>
                            <tr><td>2</td><td>Another {ent}</td><td>2026-01-02</td><td><button class='btn'>View</button></td></tr>
                        </tbody>
                    </table>
                </div>
                """
        elif route_name == "login":
            content = f"""
            <div class='card' style='max-width: 400px; margin: 4rem auto;'>
                <h2>Login</h2>
                <form>
                    <div style='margin-bottom: 1rem;'>
                        <label>Email</label><br>
                        <input type='email' style='width: 100%; padding: 0.5rem; margin-top: 0.25rem;'/>
                    </div>
                    <div style='margin-bottom: 1rem;'>
                        <label>Password</label><br>
                        <input type='password' style='width: 100%; padding: 0.5rem; margin-top: 0.25rem;'/>
                    </div>
                    <button type='button' class='btn' style='width: 100%;'>Sign In</button>
                </form>
            </div>
            """
        else:
            content = f"<div class='card'><h2>{route_name.replace('_', ' ').title()}</h2><p>Manage your {route_name} here.</p></div>"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name} - {route_name.title()}</title>
    {css}
</head>
<body>
    {header}
    <main class="container">
        {content}
    </main>
</body>
</html>"""
        return html

    def generate(self, arch: dict):
        project_name = arch.get("project_name", "GeneratedApp")
        entities = arch.get("entities", [])
        relations = arch.get("relations", [])
        routes = arch.get("routes", [])
        has_auth = arch.get("auth", False)
        
        main_path = os.path.join(self.output_dir, "main.aayu")
        views_dir = os.path.join(self.output_dir, "views")
        
        lines = []
        lines.append(f"# {project_name} - Generated by AAYU Intent-to-Silicon")
        lines.append("use http.")
        lines.append("use db.")
        
        if has_auth:
            lines.append("use auth.")
            
        lines.append("")
        
        # Build relational fields map
        foreign_keys = {e: [] for e in entities}
        for rel in relations:
            if rel["type"] == "1:N":
                if rel["to"] in foreign_keys:
                    foreign_keys[rel["to"]].append(f"{rel['from'].lower()}_id")
            elif rel["type"] == "M:N":
                junc = rel["junction"]
                if junc in foreign_keys:
                    foreign_keys[junc].append(f"{rel['from'].lower()}_id")
                    foreign_keys[junc].append(f"{rel['to'].lower()}_id")
        
        # Generate Database Models
        if entities:
            for ent in entities:
                lines.append(f"entity {ent}.")
                lines.append("    text name.")
                lines.append("    text created_at.")
                
                # Append foreign keys from relations
                for fk in foreign_keys.get(ent, []):
                    lines.append(f"    number {fk}.")
                    
                lines.append("end.")
                lines.append("")
                
        # Generate Web Routes
        for route in routes:
            route_name = route.strip("/").replace("/", "_")
            if not route_name:
                route_name = "index"
                
            lines.append(f"task handle_{route_name} with req.")
            lines.append(f"    return render \"{route_name}.html\".")
            lines.append("end.")
            lines.append("")
            
            lines.append(f"route \"{route}\" to handle_{route_name}.")
            lines.append("")
            
        lines.append("serve on 8080.")
        
        with open(main_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            
        # 2. Generate Views (Frontend Templates)
        os.makedirs(views_dir, exist_ok=True)
        for route in routes:
            route_name = route.strip("/").replace("/", "_")
            if not route_name:
                route_name = "index"
                
            view_path = os.path.join(views_dir, f"{route_name}.html")
            with open(view_path, "w", encoding="utf-8") as f:
                html_content = self.get_template_content(project_name, route_name, entities, has_auth)
                f.write(html_content)

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python -m intent_engine.code_generator <architecture.json>")
        sys.exit(1)
        
    arch_file = sys.argv[1]
    with open(arch_file, "r") as f:
        arch = json.load(f)
        
    generator = CodeGenerator()
    generator.generate(arch)
    print("Project generated successfully!")
