/* eslint-disable */
"use client";
import { FileJson, Building2, HeartPulse, ShoppingCart, MessageSquare, Briefcase, Calculator, ArrowRight, GitBranch, Download } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const EXAMPLES = [
  { id: "hospital", title: "Hospital ERP", icon: HeartPulse, color: "text-rose-400", bg: "bg-rose-500/10", border: "border-rose-500/20", desc: "Patient management, scheduling, and medical records with strict data isolation." },
  { id: "banking", title: "Banking Core", icon: Building2, color: "text-blue-400", bg: "bg-blue-500/10", border: "border-blue-500/20", desc: "High-throughput ledger system with ACID transactions and double-entry accounting." },
  { id: "ecommerce", title: "E-Commerce", icon: ShoppingCart, color: "text-emerald-400", bg: "bg-emerald-500/10", border: "border-emerald-500/20", desc: "Inventory, cart, and order orchestration built for massive horizontal scaling." },
  { id: "crm", title: "Global CRM", icon: Briefcase, color: "text-purple-400", bg: "bg-purple-500/10", border: "border-purple-500/20", desc: "Customer relationship pipelines, sales tracking, and multi-tenant isolation." },
  { id: "chat", title: "Realtime Chat", icon: MessageSquare, color: "text-cyan-400", bg: "bg-cyan-500/10", border: "border-cyan-500/20", desc: "WebSocket driven actor model for handling millions of concurrent connections." },
  { id: "ai-agent", title: "AI Agent Platform", icon: Calculator, color: "text-yellow-400", bg: "bg-yellow-500/10", border: "border-yellow-500/20", desc: "Task queue and orchestration pipeline for autonomous LLM agents." }
];

export default function ExamplesGallery() {
  return (
    <main className="min-h-screen bg-[#050505] text-white pt-24 pb-24">
      <div className="container mx-auto px-4 max-w-6xl">
        <div className="mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold mb-4">Examples Gallery</h1>
          <p className="text-xl text-zinc-400 max-w-2xl">
            Production-ready architectural templates generated by BrainOS and optimized by the AAYU Compiler.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {EXAMPLES.map(ex => (
            <div key={ex.id} className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 hover:border-white/20 transition-all flex flex-col group">
              <div className="w-12 h-12 rounded-xl border flex items-center justify-center">
                <ex.icon className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold mb-3">{ex.title}</h3>
              <p className="text-sm text-zinc-400 mb-6 flex-1">{ex.desc}</p>
              
              <div className="flex items-center gap-3 mt-auto pt-6 border-t border-white/5">
                <Button disabled variant="outline" className="flex-1 bg-transparent border-white/10 text-xs text-zinc-500 cursor-not-allowed">
                  <Download className="w-3 h-3 mr-2" /> Download
                </Button>
                <Link href="https://github.com/Minato95-ayu/AAYU/tree/main/examples/" target="_blank" className="flex-1">
                  <Button variant="outline" className="w-full bg-transparent border-white/10 text-xs hover:bg-white/5">
                    <GitBranch className="w-3 h-3 mr-2" /> Source
                  </Button>
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}