import unittest
from compiler.lexer.lexer import Lexer
from compiler.parser.parser import Parser
from compiler.ir.cfg_builder import CFGBuilder
from compiler.ir.ssa import SSABuilder
from compiler.ir.optimizer import SSAOptimizer
from compiler.ir.linearizer import Linearizer
from compiler.bytecode.encoder import BytecodeEncoder
from runtime.vm.vm import VirtualMachine
from runtime.vm.instructions import Opcode
from tests.compiler.test_helpers import CompilerE2EMixin

class TestR61Arrays(CompilerE2EMixin, unittest.TestCase):
    
    def test_array_creation_sizes(self):
        """Test array creation with different sizes: 0, 1, 3, 5 elements."""
        cases = [
            ("[]", []),
            ("[42]", [42]),
            ("[1, 2, 3]", [1, 2, 3]),
            ("[1, 2, 3, 4, 5]", [1, 2, 3, 4, 5])
        ]
        
        for source_array, expected_result in cases:
            source = f"let a = {source_array}\nprint(a)"
            result = self.execute_aayu(source)
            self.assertEqual(result[0], str(expected_result))
            
    def test_nested_array(self):
        """Test that nested arrays are evaluated correctly (recursive stack behavior)."""
        source = "let a = [[1, 2], [3, 4]]\nprint(a)"
        result = self.execute_aayu(source)
        self.assertEqual(result[0], str([[1, 2], [3, 4]]))
        
    def test_isa_invariant(self):
        """Verify that the generated bytecode uses CREATE_ARRAY and NEVER BUILD_WIDGET."""
        source = "let a = [10, 20, 30]"
        
        from compiler.semantic.analyzer import SemanticAnalyzer
        from compiler.ir.pipeline import IRPipeline
        
        lexer = Lexer(source)
        ast = Parser(lexer.tokenize()).parse()
        semantic_ast = SemanticAnalyzer().analyze(ast)

        pipeline = IRPipeline()
        cfg = pipeline.to_ssa_cfg(semantic_ast)
        SSAOptimizer(cfg).optimize()
        mir = Linearizer(cfg).lower()
        lir = pipeline.to_lir(mir)
        encoder = BytecodeEncoder()
        prog = encoder.encode(lir)
        bytecode = prog.bytecode
        
        # Manually inspect the bytecode array
        has_create_array = False
        has_build_widget = False
        
        i = 0
        while i < len(bytecode):
            opcode = bytecode[i]
            if opcode == Opcode.CREATE_ARRAY:
                has_create_array = True
                operand = (bytecode[i+1] << 8) | bytecode[i+2]
                self.assertEqual(operand, 3, "CREATE_ARRAY operand must match array length")
            elif opcode == Opcode.BUILD_WIDGET:
                has_build_widget = True
            
            i += 3
            
        self.assertTrue(has_create_array, "Bytecode must contain CREATE_ARRAY (0x86)")
        self.assertFalse(has_build_widget, "Bytecode must NEVER contain BUILD_WIDGET for arrays")
        
if __name__ == '__main__':
    unittest.main()
