import os
import json

def run_init(project_name: str):
    base_dir = os.path.join(os.getcwd(), project_name)
    src_dir = os.path.join(base_dir, "src")
    
    if os.path.exists(base_dir):
        print(f"Error: Directory '{project_name}' already exists.")
        return
        
    os.makedirs(src_dir)
    
    # 1. src/main.aayu
    main_aayu = """# Auto-generated by AAYU init
# Need help writing AAYU? Check out: https://github.com/Minato95-ayu/INTENT-TO-SILICON/blob/main/docs/LANGUAGE_GUIDE.md

use http.
use db.

entity User.
    text name.
    text email.
end.

page Dashboard.
end.
"""
    with open(os.path.join(src_dir, "main.aayu"), "w", encoding="utf-8") as f:
        f.write(main_aayu)
        
    # 2. aayu.config.json
    config = {
        "name": project_name,
        "version": "0.1.0",
        "author": "AAYU Developer"
    }
    with open(os.path.join(base_dir, "aayu.config.json"), "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
        
    # 3. .gitignore
    gitignore = """generated/
node_modules/
__pycache__/
.env
"""
    with open(os.path.join(base_dir, ".gitignore"), "w", encoding="utf-8") as f:
        f.write(gitignore)
        
    # 4. README.md
    readme = f"""# {project_name}

An AAYU architecture project.

## Commands
- `aayu validate src/main.aayu`: Check syntax
- `aayu generate src/main.aayu`: Build full stack project
"""
    with open(os.path.join(base_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
        
    print(f"Success! Initialized AAYU project in {base_dir}")
    print("Run the following to get started:")
    print(f"  cd {project_name}")
    print("  aayu validate src/main.aayu")
