"""
=============================================================================
FILE: self_critic.py
PURPOSE: Part of the AAYU Intent-to-Silicon project
=============================================================================
This file is part of the AAYU (Aayu) Intent-to-Silicon Programming Language.
The AAYU language enables developers to write code using natural language
intentions, which are compiled to optimized backend code.

For beginners: This file handles part of the aayu intent-to-silicon project.
To understand the project architecture, see the ARCHITECTURE_FREEZE.md file.
=============================================================================
"""

from typing import Dict, Any, List

class SelfCritic:
    """
    AI Agent responsible for reviewing code generated by BrainOS Executors.
    Acts as the 'Reviewer' in the Writer-Reviewer-Verifier triad.
    """
    def __init__(self, llm_router):
        self.llm = llm_router

    def critique(self, generated_code: str, context_task: Dict[str, Any]) -> List[str]:
        prompt = (
            "Review the following generated AAYU code for logic errors, "
            "style inconsistencies, and adherence to the task requirements.\n\n"
            f"Task context:\n{context_task}\n\n"
            f"Code:\n{generated_code}"
        )
        
        response = self.llm.generate(
            prompt=prompt,
            system_prompt="You are a strict Code Reviewer for the AAYU Language."
        )
        
        # Simulated parsing of critiques
        critiques = [line.strip() for line in response.split('\n') if line.strip().startswith('-')]
        return critiques
