import os
import json

class APIGenerator:
    def __init__(self):
        pass

    def _type_mapper(self, sql_type):
        sql_type = sql_type.upper()
        if "UUID" in sql_type: return "str"  # using str for UUID to simplify SQLite JSON serialization
        if "VARCHAR" in sql_type: return "str"
        if "STRING" in sql_type: return "str"
        if "INT" in sql_type: return "int"
        if "BOOLEAN" in sql_type: return "bool"
        if "TIMESTAMP" in sql_type or "DATE" in sql_type or "DATETIME" in sql_type: return "datetime"
        if "DECIMAL" in sql_type or "FLOAT" in sql_type: return "float"
        return "str"

    def generate_schemas(self, resolved_schema):
        code = "from pydantic import BaseModel\n"
        code += "from typing import List, Optional\n"
        code += "from datetime import datetime\n\n"
        
        for entity, definition in resolved_schema.items():
            model_name = ''.join(word.title() for word in entity.split('_'))
            
            pydantic_fields = []
            for field in definition.get("fields", []):
                py_type = self._type_mapper(field["type"])
                if not field.get("required") and not field.get("primary_key"):
                    py_type = f"Optional[{py_type}] = None"
                elif field.get("primary_key"):
                    py_type = f"Optional[{py_type}] = None" # DB handles generation
                pydantic_fields.append(f"    {field['name']}: {py_type}")
                
            if pydantic_fields:
                fields_code = "\n".join(pydantic_fields)
            else:
                fields_code = "    pass"
            
            code += f"class {model_name}Base(BaseModel):\n"
            code += fields_code + "\n\n"
            
            code += f"class {model_name}Create({model_name}Base):\n"
            code += "    pass\n\n"
            
            code += f"class {model_name}({model_name}Base):\n"
            code += "    class Config:\n"
            code += "        from_attributes = True\n\n"
            
        return code

    def generate_api_code(self, entity):
        """Generates FastAPI router with SQLAlchemy integration"""
        model_name = ''.join(word.title() for word in entity.split('_'))
        
        return f"""# TODO: Generated by Aayu Compiler
# Deterministic API Synthesis with SQLAlchemy

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

import models
import schemas
from database import get_db

router = APIRouter()

@router.post('/api/{entity}', response_model=schemas.{model_name})
def create_{entity}(item: schemas.{model_name}Create, db: Session = Depends(get_db)):
    db_item = models.{model_name}(**item.dict())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

@router.get('/api/{entity}', response_model=List[schemas.{model_name}])
def get_all_{entity}(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(models.{model_name}).offset(skip).limit(limit).all()
    return items

@router.get('/api/{entity}/{{item_id}}', response_model=schemas.{model_name})
def get_{entity}(item_id: str, db: Session = Depends(get_db)):
    item = db.query(models.{model_name}).filter(models.{model_name}.id == item_id).first()
    if item is None:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return item
"""

