import os
import json

class APIGenerator:
    def __init__(self):
        self.entity_definitions = {}
        
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        try:
            with open(os.path.join(base_dir, 'dictionary', 'entity_definitions.json'), 'r') as f:
                self.entity_definitions = json.load(f)
        except Exception as e:
            print(f"Warning: Could not load entity_definitions.json: {e}")

    def _type_mapper(self, sql_type):
        sql_type = sql_type.upper()
        if "UUID" in sql_type: return "UUID"
        if "VARCHAR" in sql_type: return "str"
        if "INT" in sql_type: return "int"
        if "BOOLEAN" in sql_type: return "bool"
        if "TIMESTAMP" in sql_type or "DATE" in sql_type: return "datetime"
        if "DECIMAL" in sql_type: return "float"
        return "str"

    def generate_api_code(self, entity):
        """Generates FastAPI code with Pydantic models for a given entity"""
        definition = self.entity_definitions.get(entity)
        if not definition:
            # Fallback simple template
            return f"""from fastapi import APIRouter

router = APIRouter()

@router.get('/api/{entity}')
def get_{entity}():
    # TODO: Simple fallback generated by Aayu
    return {{'status': 'ok'}}
"""

        model_name = ''.join(word.title() for word in entity.split('_'))
        
        pydantic_fields = []
        for field in definition.get("fields", []):
            py_type = self._type_mapper(field["type"])
            if not field.get("required") and not field.get("primary_key"):
                py_type = f"Optional[{py_type}]"
            pydantic_fields.append(f"    {field['name']}: {py_type}")
            
        fields_code = "\n".join(pydantic_fields)
        
        return f"""# TODO: Generated by Aayu Compiler
# Deterministic API Synthesis

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional
from uuid import UUID
from datetime import datetime

class {model_name}(BaseModel):
{fields_code}

class {model_name}Create(BaseModel):
    # Exclude ID and system fields for creation
{fields_code}

router = APIRouter()

# Mock DB
db_storage = []

@router.post('/api/{entity}', response_model={model_name})
def create_{entity}(item: {model_name}Create):
    new_item = item.dict()
    new_item['id'] = 'mocked-uuid'
    db_storage.append(new_item)
    return new_item

@router.get('/api/{entity}', response_model=List[{model_name}])
def get_all_{entity}():
    return db_storage

@router.get('/api/{entity}/{{item_id}}', response_model={model_name})
def get_{entity}(item_id: str):
    for item in db_storage:
        if item.get("id") == item_id:
            return item
    raise HTTPException(status_code=404, detail="{model_name} not found")
"""
