"""
Aayu App Packager (Sprint 30)

Orchestrates all generators to write a runnable FastAPI project directory.
"""
import os
from .schema_nodes import SchemaModel
from .database_generator import DatabaseGenerator
from .sqlalchemy_generator import SQLAlchemyGenerator
from .pydantic_generator import PydanticGenerator
from .router_generator import RouterGenerator
from .main_generator import MainGenerator

class AppPackager:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    def package(self, schema: SchemaModel):
        # Create root directory
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Write root module init
        with open(os.path.join(self.output_dir, "__init__.py"), "w") as f:
            f.write("")
            
        # Write database.py
        db_code = DatabaseGenerator().generate()
        with open(os.path.join(self.output_dir, "database.py"), "w") as f:
            f.write(db_code)
            
        # Write models.py
        models_code = SQLAlchemyGenerator().generate(schema)
        with open(os.path.join(self.output_dir, "models.py"), "w") as f:
            f.write(models_code)
            
        # Write schemas.py
        schemas_code = PydanticGenerator().generate(schema)
        with open(os.path.join(self.output_dir, "schemas.py"), "w") as f:
            f.write(schemas_code)
            
        # Write routers/
        routers_dir = os.path.join(self.output_dir, "routers")
        os.makedirs(routers_dir, exist_ok=True)
        
        # Write routers/__init__.py
        with open(os.path.join(routers_dir, "__init__.py"), "w") as f:
            f.write("")
            
        routers_dict = RouterGenerator().generate(schema)
        for filename, router_code in routers_dict.items():
            with open(os.path.join(routers_dir, filename), "w") as f:
                f.write(router_code)
                
        # Write main.py
        main_code = MainGenerator().generate(schema)
        with open(os.path.join(self.output_dir, "main.py"), "w") as f:
            f.write(main_code)
            
        # Write requirements.txt
        with open(os.path.join(self.output_dir, "requirements.txt"), "w") as f:
            f.write("fastapi\nhttpx\npydantic\nsqlalchemy\nuvicorn\n")
            
        # Write README.md
        readme = [
            "# Generated by Aayu\n",
            "## Install\n",
            "```bash",
            "pip install -r requirements.txt",
            "```\n",
            "## Run\n",
            "```bash",
            "uvicorn main:app --reload",
            "```\n",
            "## API Docs\n",
            "http://localhost:8000/docs"
        ]
        with open(os.path.join(self.output_dir, "README.md"), "w") as f:
            f.write("\n".join(readme))
