import os
import json

class DatabaseGenerator:
    def __init__(self):
        self.entity_definitions = {}
        
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        try:
            with open(os.path.join(base_dir, 'dictionary', 'entity_definitions.json'), 'r') as f:
                self.entity_definitions = json.load(f)
        except Exception as e:
            print(f"Warning: Could not load entity_definitions.json: {e}")

    def generate_sql(self, entities):
        sql = "-- TODO: Generated by Aayu Compiler\n-- Deterministic Database Synthesis\n\n"
        
        for entity in entities:
            definition = self.entity_definitions.get(entity)
            if not definition:
                # Fallback to simple table if definition is missing
                sql += f"CREATE TABLE IF NOT EXISTS {entity} (\n"
                sql += "    id UUID PRIMARY KEY,\n"
                sql += "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
                sql += ");\n\n"
                continue
                
            sql += f"CREATE TABLE IF NOT EXISTS {entity} (\n"
            fields = definition.get("fields", [])
            
            field_lines = []
            for field in fields:
                line = f"    {field['name']} {field['type']}"
                if field.get("primary_key"):
                    line += " PRIMARY KEY"
                if field.get("unique"):
                    line += " UNIQUE"
                if field.get("required"):
                    line += " NOT NULL"
                if field.get("default"):
                    line += f" DEFAULT {field['default']}"
                if field.get("foreign_key"):
                    ref_table, ref_col = field["foreign_key"].split('.')
                    line += f" REFERENCES {ref_table}({ref_col})"
                
                field_lines.append(line)
                
            sql += ",\n".join(field_lines)
            sql += "\n);\n\n"
            
        return sql
