import os
import json

class FrontendGenerator:
    def __init__(self):
        pass

    def generate_component_code(self, module_name, entities_in_context, resolved_schema):
        """Generates a React component dynamically, using the resolved schema."""
        
        component_name = ''.join(word.title() for word in module_name.split('_'))
        
        # Try to find a matching entity for this module (e.g. library_booking for booking_form)
        matched_entity = None
        for entity in entities_in_context:
            # simple heuristic: if entity name is part of module name or vice-versa
            if entity.split('_')[0] in module_name or module_name.split('_')[0] in entity:
                matched_entity = entity
                break
                
        # If it's a form or list, we can generate dynamic props
        if matched_entity and "form" in module_name.lower():
            return self._generate_form(component_name, matched_entity, resolved_schema)
        elif matched_entity and "list" in module_name.lower():
            return self._generate_list(component_name, matched_entity, resolved_schema)
        else:
            return self._generate_basic_component(component_name)

    def _generate_basic_component(self, name):
        return f"""import React from 'react';

// TODO: Generated by Aayu Compiler
export default function {name}() {{
  return (
    <div className="{name.lower()}-container">
      <h1>{name}</h1>
    </div>
  );
}}
"""

    def _generate_form(self, component_name, entity, resolved_schema):
        definition = resolved_schema.get(entity, {})
        fields = definition.get("fields", [])
        
        form_elements = []
        for field in fields:
            if field['name'] in ['id', 'created_at']: continue
            
            input_type = "text"
            if "DATE" in field['type'].upper() or "TIMESTAMP" in field['type'].upper(): input_type = "date"
            if "INT" in field['type'].upper() or "DECIMAL" in field['type'].upper() or "FLOAT" in field['type'].upper(): input_type = "number"
            
            form_elements.append(f"""        <div className="form-group">
          <label>{field['name'].replace('_', ' ').title()}</label>
          <input type="{input_type}" name="{field['name']}" required={{{str(field.get('required', False)).lower()}}} />
        </div>""")
        
        elements_str = "\n".join(form_elements)
        
        return f"""import React, {{ useState }} from 'react';

// TODO: Generated by Aayu Compiler (Deterministic UI Synthesis)
export default function {component_name}() {{
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {{
    e.preventDefault();
    setLoading(true);
    // Submit to /api/{entity}
    setLoading(false);
  }};

  return (
    <div className="form-container">
      <h2>Create {entity.replace('_', ' ').title()}</h2>
      <form onSubmit={{handleSubmit}}>
{elements_str}
        <button type="submit" disabled={{loading}}>Submit</button>
      </form>
    </div>
  );
}}
"""

    def _generate_list(self, component_name, entity, resolved_schema):
        definition = resolved_schema.get(entity, {})
        fields = definition.get("fields", [])
        
        headers = []
        cells = []
        for field in fields:
            headers.append(f"            <th>{field['name'].replace('_', ' ').title()}</th>")
            cells.append(f"            <td>{{item.{field['name']}}}</td>")
            
        headers_str = "\n".join(headers)
        cells_str = "\n".join(cells)
        
        return f"""import React, {{ useEffect, useState }} from 'react';

// TODO: Generated by Aayu Compiler (Deterministic UI Synthesis)
export default function {component_name}() {{
  const [data, setData] = useState<any[]>([]);

  useEffect(() => {{
    // Fetch from /api/{entity}
    setData([]);
  }}, []);

  return (
    <div className="list-container">
      <h2>{entity.replace('_', ' ').title()} List</h2>
      <table>
        <thead>
          <tr>
{headers_str}
          </tr>
        </thead>
        <tbody>
          {{data.map(item => (
            <tr key={{item.id}}>
{cells_str}
            </tr>
          ))}}
        </tbody>
      </table>
    </div>
  );
}}
"""
