import os
import json

class FrontendGenerator:
    def __init__(self):
        pass

    def generate_component_code(self, module_name, entities_in_context, resolved_schema):
        """Generates a React component dynamically, using the resolved schema."""
        
        component_name = ''.join(word.title() for word in module_name.split('_'))
        
        # Try to find a matching entity for this module (e.g. library_booking for booking_form)
        matched_entity = None
        for entity in entities_in_context:
            # simple heuristic: if entity name is part of module name or vice-versa
            if entity.split('_')[0] in module_name or module_name.split('_')[0] in entity:
                matched_entity = entity
                break
                
        # If it's a form or list, we can generate dynamic props
        if matched_entity and "form" in module_name.lower():
            return self._generate_form(component_name, matched_entity, resolved_schema)
        elif matched_entity and "list" in module_name.lower():
            return self._generate_list(component_name, matched_entity, resolved_schema)
        else:
            return self._generate_basic_component(component_name)

    def _generate_basic_component(self, name):
        return f"""import React from 'react';

// TODO: Generated by Aayu Compiler
export default function {name}() {{
  return (
    <div className="{name.lower()}-container">
      <h1>{name}</h1>
    </div>
  );
}}
"""

    def _generate_form(self, component_name, entity, resolved_schema):
        definition = resolved_schema.get(entity, {})
        fields = definition.get("fields", [])
        
        state_init = []
        form_elements = []
        for field in fields:
            if field['name'] in ['id', 'created_at']: continue
            
            input_type = "text"
            if "DATE" in field['type'].upper() or "TIMESTAMP" in field['type'].upper(): input_type = "date"
            if "INT" in field['type'].upper() or "DECIMAL" in field['type'].upper() or "FLOAT" in field['type'].upper(): input_type = "number"
            
            state_init.append(f"{field['name']}: ''")
            
            form_elements.append(f"""        <div className="form-group" style={{{{ marginBottom: '10px' }}}}>
          <label style={{{{ display: 'block', marginBottom: '5px' }}}}>{field['name'].replace('_', ' ').title()}</label>
          <input 
            type="{input_type}" 
            name="{field['name']}" 
            value={{formData.{field['name']}}}
            onChange={{handleChange}}
            required={{{str(field.get('required', False)).lower()}}} 
            style={{{{ width: '100%', padding: '8px' }}}}
          />
        </div>""")
        
        elements_str = "\n".join(form_elements)
        state_init_str = "{" + ", ".join(state_init) + "}"
        
        return f"""import React, {{ useState }} from 'react';

// TODO: Generated by Aayu Compiler (Deterministic UI Synthesis)
export default function {component_name}() {{
  const [formData, setFormData] = useState({state_init_str});
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  const handleChange = (e: any) => {{
    const {{ name, value }} = e.target;
    // Basic type coercion for number inputs to satisfy API schema
    const parsedValue = e.target.type === 'number' && value !== '' ? Number(value) : value;
    setFormData(prev => ({{ ...prev, [name]: parsedValue }}));
  }};

  const handleSubmit = async (e: React.FormEvent) => {{
    e.preventDefault();
    setLoading(true);
    setMessage('');
    try {{
      const response = await fetch('/api/{entity}', {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify(formData)
      }});
      if (!response.ok) throw new Error('Failed to create {entity}');
      setMessage('Successfully created {entity}!');
      setFormData({state_init_str});
    }} catch (error: any) {{
      setMessage(error.message);
    }} finally {{
      setLoading(false);
    }}
  }};

  return (
    <div className="form-container" style={{{{ border: '1px solid #ccc', padding: '20px', borderRadius: '8px', maxWidth: '400px' }}}}>
      <h2>Create {entity.replace('_', ' ').title()}</h2>
      {{message && <p style={{{{ color: message.includes('Success') ? 'green' : 'red' }}}}>{{message}}</p>}}
      <form onSubmit={{handleSubmit}}>
{elements_str}
        <button type="submit" disabled={{loading}} style={{{{ marginTop: '10px', padding: '10px 15px', cursor: 'pointer' }}}}>
          {{loading ? 'Submitting...' : 'Submit'}}
        </button>
      </form>
    </div>
  );
}}
"""

    def _generate_list(self, component_name, entity, resolved_schema):
        definition = resolved_schema.get(entity, {})
        fields = definition.get("fields", [])
        
        headers = []
        cells = []
        for field in fields:
            headers.append(f"            <th style={{{{ padding: '8px', borderBottom: '1px solid #ccc' }}}}>{field['name'].replace('_', ' ').title()}</th>")
            cells.append(f"            <td style={{{{ padding: '8px', borderBottom: '1px solid #eee' }}}}>{{item.{field['name']}}}</td>")
            
        headers_str = "\n".join(headers)
        cells_str = "\n".join(cells)
        
        return f"""import React, {{ useEffect, useState }} from 'react';

// TODO: Generated by Aayu Compiler (Deterministic UI Synthesis)
export default function {component_name}() {{
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchData = async () => {{
    try {{
      setLoading(true);
      const response = await fetch('/api/{entity}');
      if (!response.ok) throw new Error('Failed to fetch {entity} data');
      const result = await response.json();
      setData(result);
    }} catch (err: any) {{
      setError(err.message);
    }} finally {{
      setLoading(false);
    }}
  }};

  useEffect(() => {{
    fetchData();
  }}, []);

  return (
    <div className="list-container" style={{{{ marginTop: '20px' }}}}>
      <h2>{entity.replace('_', ' ').title()} List</h2>
      <button onClick={{fetchData}} style={{{{ marginBottom: '10px', padding: '5px 10px', cursor: 'pointer' }}}}>Refresh Data</button>
      {{error && <p style={{{{ color: 'red' }}}}>{{error}}</p>}}
      {{loading ? <p>Loading...</p> : (
        <table style={{{{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}}}>
          <thead>
            <tr>
{headers_str}
            </tr>
          </thead>
          <tbody>
            {{data.map((item, index) => (
              <tr key={{item.id || index}}>
{cells_str}
              </tr>
            ))}}
            {{data.length === 0 && (
              <tr>
                <td colSpan={{{len(fields)}}} style={{{{ textAlign: 'center', padding: '20px' }}}}>No records found.</td>
              </tr>
            )}}
          </tbody>
        </table>
      )}}
    </div>
  );
}}
"""
