"""
Aayu Grammar Generator v0.1

Converts a ResolvedIntent (locked intent) into Aayu ADL (.aayu) syntax.

Pipeline position:
    Intent → Clarification → Lock → Validation → GrammarGenerator → .aayu file

This generator proves that Aayu's internal graph representations
map cleanly to the formal Architecture Definition Language.
"""

from typing import List, Set, Dict
from .clarification_engine import ClarificationEngine, ClarificationResult, ResolvedIntent
from .concept_graph_engine import ConceptGraphEngine


# Known cross-cutting features (not domain-specific entities)
KNOWN_FEATURES = {
    "authentication", "payments", "billing", "notifications", "compliance",
    "telemedicine", "tracking", "offline_support", "routing", "localization",
    "accessibility", "fraud_detection", "content_delivery", "media_sharing",
    "push_notifications", "subscriptions", "maintenance", "interviews",
    "digital_content", "insurance"
}


class GrammarGenerator:
    """
    Takes a ResolvedIntent and generates Aayu Grammar v0.1 (.aayu) syntax.
    """

    def __init__(self):
        self.graph_engine = ConceptGraphEngine()

    def generate(self, resolved_intent: ResolvedIntent,
                 clarification_result: ClarificationResult,
                 system_name: str = "App") -> str:
        """
        Generates .aayu syntax from a locked ResolvedIntent.

        Args:
            resolved_intent: The locked, validated ResolvedIntent.
            clarification_result: The ClarificationResult (for detected domains).
            system_name: The name of the system (derived from intent).

        Returns:
            A string containing valid .aayu syntax.
        """
        domains = clarification_result.detected_domains
        if not domains and resolved_intent.domain and resolved_intent.domain != "unknown":
            domains = [resolved_intent.domain]

        # Collect all entities per domain from the concept graph
        domain_entities: Dict[str, Set[str]] = {}
        for d in domains:
            inferred, _ = self.graph_engine.expand([d])
            # Remove the domain itself from inferred set
            entities_for_domain = {e for e in inferred if e != d and e not in KNOWN_FEATURES}
            domain_entities[d] = entities_for_domain

        # Find shared entities (appear in 2+ domains)
        entity_count: Dict[str, int] = {}
        for d, entities in domain_entities.items():
            for e in entities:
                entity_count[e] = entity_count.get(e, 0) + 1

        shared_entities = sorted([e for e, count in entity_count.items() if count > 1])

        # Domain-specific entities (not shared)
        specific_entities = set()
        for d, entities in domain_entities.items():
            for e in entities:
                if e not in shared_entities:
                    specific_entities.add(e)
        specific_entities = sorted(specific_entities)

        # Features from confirmed + inferred that are in KNOWN_FEATURES
        all_concepts = set(resolved_intent.detected + resolved_intent.inferred + resolved_intent.confirmed)
        features = sorted([c for c in all_concepts if c in KNOWN_FEATURES and c not in domains])

        # Relations: shared entities -> domain-specific entities
        relations = []
        if shared_entities:
            primary_shared = shared_entities[0]  # e.g., 'student'
            for entity in specific_entities:
                relations.append((primary_shared, entity))
        else:
            # For single-domain: use first required entity as hub
            all_entities = shared_entities + specific_entities
            if len(all_entities) >= 2:
                hub = all_entities[0]
                for entity in all_entities[1:]:
                    relations.append((hub, entity))

        # Build .aayu output
        lines = []
        lines.append(f"# {system_name}")
        lines.append(f"# Generated by Aayu Grammar v0.1")
        lines.append("")
        lines.append(f"system {system_name}")
        lines.append("")

        # Domains
        lines.append("domains:")
        for d in sorted(domains):
            lines.append(f"  {d}")
        lines.append("")

        # Shared (only if multi-domain with shared entities)
        if shared_entities:
            lines.append("shared:")
            for e in shared_entities:
                lines.append(f"  {e}")
            lines.append("")

        # Entities
        if specific_entities:
            lines.append("entities:")
            for e in specific_entities:
                lines.append(f"  {e}")
            lines.append("")

        # Features
        if features:
            lines.append("features:")
            for f in features:
                lines.append(f"  {f}")
            lines.append("")

        # Relations
        if relations:
            lines.append("relations:")
            for src, tgt in relations:
                lines.append(f"  {src} -> {tgt}")
            lines.append("")

        return "\n".join(lines)
