import os

class ProjectScaffoldGenerator:
    """
    Writes the AAYU entities to disk in a structured folder format.
    """
    def generate(self, project_name: str, entities: dict, output_dir: str = "./output"):
        project_dir = os.path.join(output_dir, project_name.replace(" ", "_").lower())
        os.makedirs(project_dir, exist_ok=True)
        
        src_dir = os.path.join(project_dir, "src")
        os.makedirs(src_dir, exist_ok=True)
        
        for entity_name, fields in entities.items():
            file_path = os.path.join(src_dir, f"{entity_name.lower()}.aayu")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"entity {entity_name}\nhas\n")
                for field in fields:
                    f.write(f"    {field}\n")
                f.write("end.\n")
                
        main_path = os.path.join(src_dir, "main.aayu")
        with open(main_path, "w", encoding="utf-8") as f:
            f.write("// Generated by BrainOS\n\n")
            for entity_name in entities.keys():
                f.write(f'import "{entity_name.lower()}".\n')
            f.write("\nfn main()\ndo\n")
            f.write(f'    print("Starting {project_name} Architecture...").\n')
            f.write("end.\n")
            
        return project_dir
