import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom'

// Page Imports
${page_imports}

function App() {
  return (
    <Router>
      <div className="min-h-screen flex flex-col">
        <header className="bg-indigo-600 text-white p-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">${app_name}</h1>
            <nav className="space-x-4">
${nav_links}
            </nav>
          </div>
        </header>
        
        <main className="flex-grow container mx-auto p-4 mt-6">
          <Routes>
${routes}
            <Route path="*" element={<div className="text-center mt-20"><h2 className="text-2xl font-bold text-gray-700">404 Not Found</h2><p className="text-gray-500 mt-2">The requested page does not exist in this AAYU app.</p></div>} />
          </Routes>
        </main>
        
        <footer className="bg-gray-100 p-4 text-center text-gray-500 text-sm mt-auto">
          Generated by AAYU Intent-to-Silicon Platform
        </footer>
      </div>
    </Router>
  )
}

export default App
