import os
from generators.base import BaseGenerator

class OrchestratorGenerator(BaseGenerator):
    def __init__(self, ir_data: dict, output_dir: str):
        super().__init__(ir_data, output_dir)

    def generate(self):
        print(f"Generating Orchestrator files in {self.output_dir}...")
        
        app_name = self.ir.get("system", {}).get("name", "AAYU App")

        # 1. Generate docker-compose.yml
        docker_compose = f"""version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/{app_name.lower().replace(' ', '_')}
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: {app_name.lower().replace(' ', '_')}
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
"""
        self.write_file("docker-compose.yml", docker_compose)

        # 2. Generate .env.example
        env_example = f"""# Auto-generated by AAYU
DATABASE_URL=postgres://user:password@localhost:5432/{app_name.lower().replace(' ', '_')}
PORT=8000
FRONTEND_URL=http://localhost:3000
"""
        self.write_file(".env.example", env_example)

        # 3. Generate README.md
        readme = f"""# {app_name}

> Auto-generated full-stack application by **AAYU v1**.

## Project Overview
This project was scaffolded via **Intent-to-Silicon** architecture. 
The entire codebase was deterministically generated from your `.aayu` schema files.

## Architecture

- **Frontend:** React + Vite (Port 3000)
- **Backend:** FastAPI (Port 8000)
- **Database:** PostgreSQL 15 (Port 5432)

## 1. Local Setup

### Frontend (React)
```bash
cd frontend
npm install
npm run dev
```

### Backend (FastAPI)
```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```

### Database (PostgreSQL)
Load `database/schema.sql` into your local Postgres instance or run via Docker.

## 2. Docker Setup (Recommended)

To spin up the entire stack seamlessly:
```bash
docker-compose up --build
```

Access the application at `http://localhost:3000`.
"""
        self.write_file("README.md", readme)
        print("Orchestrator generation complete.")
