import os

filepath = r'd:\intent-to-silicon-research\INTENT-TO-SILICON\website\app\docs\[...slug]\page.tsx'
os.makedirs(os.path.dirname(filepath), exist_ok=True)

content = '''
"use client";

import { CodeBlock, ErrorBlock, PipelineDiagram, PageNav } from "@/components/docs/DocsComponents";
import { AlertTriangle, Lightbulb } from "lucide-react";

export default function DocPage({ params }: { params: { slug: string[] } }) {
  const path = params.slug.join("/");

  // Content Registry based on Path
  if (path === "language/syntax") {
    return (
      <>
        <h1>Syntax Basics</h1>
        <p className="lead">AAYU uses a clean, keyword-driven syntax. Unlike C or Java, statements are terminated with a period (<code>.</code>).</p>
        
        <h2>Entity Declarations</h2>
        <p>Entities are the core structs in AAYU. They hold state.</p>
        <CodeBlock 
          code={\entity User\\nhas\\n    name: Text\\n    age: Number\\nend.\} 
          playgroundUrl="/playground"
        />

        <h2>Common Errors</h2>
        <p>A frequent mistake for beginners is forgetting the terminating period.</p>
        <ErrorBlock 
          wrong={\entity User\\nhas\\n    name: Text\\nend\}
          correct={\entity User\\nhas\\n    name: Text\\nend.\}
          errorMsg="SyntaxError: Expected '.' at the end of declaration block."
        />

        <h2>Methods & Extensions</h2>
        <p>You attach behavior to entities using the <code>extend</code> keyword.</p>
        <CodeBlock 
          code={\extend User\\nhas\\n    fn grow_older()\\n    do\\n        self.age = self.age + 1.\\n    end.\\nend.\}
        />

        <PageNav 
          prev={{ title: "Hello World", href: "/docs/getting-started/hello-world" }}
          next={{ title: "Variables", href: "/docs/language/variables" }}
        />
      </>
    );
  }

  if (path === "compiler/ast") {
    return (
      <>
        <h1>Abstract Syntax Tree (AST)</h1>
        <p className="lead">The AST is the structural representation of your source code generated by the Parser.</p>
        
        <PipelineDiagram stages={["Source", "Lexer", "Parser", "AST", "Semantic"]} />

        <h2>Understanding AST Nodes</h2>
        <p>Every node in AAYU inherits from a base <code>ASTNode</code>. The primary node for a file is the <code>ProgramNode</code>.</p>
        <CodeBlock 
          lang="json"
          code={\{\\n  "type": "ProgramNode",\\n  "body": [\\n    {\\n      "type": "EntityNode",\\n      "name": "User"\\n    }\\n  ]\\n}\} 
        />

        <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 my-6 flex gap-4">
          <Lightbulb className="w-6 h-6 text-blue-400 shrink-0" />
          <div>
            <h4 className="text-blue-400 font-bold mb-1">Architecture Tip</h4>
            <p className="text-zinc-300 text-sm">
              BrainOS directly operates on the AAYU AST before compilation to perform security checks and architectural tradeoffs. You can hook into this via the Intent Engine APIs.
            </p>
          </div>
        </div>

        <PageNav 
          prev={{ title: "Parser", href: "/docs/compiler/parser" }}
          next={{ title: "Semantic Analysis", href: "/docs/compiler/semantic" }}
        />
      </>
    );
  }

  // Fallback for WIP pages
  return (
    <>
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded bg-yellow-500/10 border border-yellow-500/20 text-yellow-500 text-xs font-bold mb-6">
        <AlertTriangle className="w-4 h-4" /> Documentation in Progress
      </div>
      <h1 className="capitalize">{params.slug[params.slug.length - 1].replace("-", " ")}</h1>
      <p className="text-zinc-400">
        This page is currently being drafted by the AAYU team and will be available in the upcoming v1.0 release.
      </p>
      
      <div className="mt-12">
        <PipelineDiagram stages={["Drafting", "Review", "Publishing"]} />
      </div>
    </>
  );
}
'''

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Created dynamic docs content page.")
