import os

docs_dir = r'd:\intent-to-silicon-research\INTENT-TO-SILICON\docs'

files = {
    'installation.md': '''# Installation Guide

Welcome to AAYU! AAYU provides pre-compiled binaries for Windows, macOS, and Linux.

## Quick Install (Windows)
Download the ayu-v1.0.0-windows-x64.zip release and add the extracted folder to your System PATH.
Alternatively, use the AAYU Installer:
`powershell
Invoke-WebRequest -Uri "https://aayu.dev/install.ps1" -OutFile "install.ps1"; .\install.ps1
`

## Quick Install (macOS / Linux)
`ash
curl -fsSL https://aayu.dev/install.sh | bash
`

## Verify Installation
`ash
aayu --version
# Expected: AAYU Language CLI (v1.0.0 Stable)
`
''',

    'language-guide.md': '''# Language Guide

AAYU is a deterministic, strictly-typed language optimized for AI compilation.

## Basic Syntax
All statements must end with a period (.) unless they open a block (e.g., do, has).

`ayu
// Variables
let x: Number = 10.
mut y: Number = 20.

// Functions
fn calculate_total(price: Number, tax: Number) -> Number do
    return price + tax.
end.

// Entities (Data Structures)
entity User has
    id: Number
    name: Text
end.
`
''',

    'compiler-architecture.md': '''# Compiler Architecture

The AAYU compiler is a multi-pass pipeline written in Python (soon porting to Rust).

## 1. Lexer (lexer.py)
Converts raw string input into a stream of semantic Tokens, identifying identifiers, numbers, texts, and structural keywords (let, mut, n).

## 2. Parser (parser.py)
Consumes the token stream and builds an Abstract Syntax Tree (AST). It enforces strict syntactical rules like mandatory periods for statements.

## 3. Semantic Analyzer (semantic.py)
Performs static type checking, scope resolution, and validates symbol definitions.

## 4. Bytecode Generator (compiler.py)
Compiles the validated AST down to a custom AAYU Instruction Set Architecture (ISA), ready for VM execution.
''',

    'runtime.md': '''# Runtime (AAYU VM)

The AAYU Virtual Machine executes the custom bytecode generated by the compiler.

## Stack-Based Execution
The VM (m.py) is a stack-based machine. Instructions push and pop RuntimeValue objects (e.g., NumberValue, TextValue) onto the stack.

## Deterministic Memory
AAYU utilizes Deterministic Automatic Reference Counting (DARC). There is no non-deterministic Garbage Collector pause. Memory is managed deterministically at compile time through scope analysis and reference tracking.
''',

    'brainos.md': '''# BrainOS

BrainOS is AAYU's architecture-generation intelligence layer.

## How it Works
1. **Decision Engine**: Reads parsed Intent IR to detect cross-domain constraints (e.g., "High Read Throughput" + "CRM").
2. **Recommendation Engine**: Selects the optimal software architecture (e.g., Edge-Cached Serverless Monolith).
3. **Cost Engine**: Projects monthly infrastructure costs based on the architecture.
4. **Security & Performance Review**: Scans the generated logical entities for vulnerabilities (PII) and performance bottlenecks.
5. **Project Scaffold Generator**: Writes the physical folder structure and initial .aayu code to disk.
''',

    'intent-engine.md': '''# Intent Engine

The Intent Engine translates raw human language into structured JSON IR.

## Pipeline
1. **Offline NLP**: Performs tokenization, stop-word removal, POS tagging, and entity extraction without external API dependencies.
2. **Knowledge Graph**: Resolves domain synonyms and injects structural requirements.
3. **Clarification Engine**: Detects missing business logic (e.g., requesting an Ecommerce app without specifying a Payment Gateway) and flags it for the developer.

## Output JSON IR
The output is consumed by BrainOS.
''',

    'package-manager.md': '''# Package Manager

AAYU uses ayu-pm for dependency management.

## Initializing a project
`ash
aayu init my_app
`

## Installing a Package
`ash
aayu add http_server
`

Dependencies are tracked deterministically in ayu.toml.
''',

    'cli-reference.md': '''# CLI Reference

The ayu command-line tool manages your entire workflow.

- ayu init <name>: Scaffold a new project.
- ayu run <file>: Compile and execute an .aayu script via the VM.
- ayu fmt <file>: Auto-format your code to the strict 4-space indent standard.
- ayu lint <file>: Run static analysis to catch missing types or terminating periods.
''',

    'vscode-extension-guide.md': '''# VS Code Extension

The official AAYU VS Code Extension provides a seamless developer experience powered by the AAYU Language Server Protocol (LSP).

## Features
- **Syntax Highlighting**: Full grammar support for .aayu files.
- **Diagnostics**: Real-time linting errors (e.g., missing types).
- **Formatting**: Format document on save.

## Installation
Search for AAYU Language Support in the VS Code Marketplace or download the .vsix file from our GitHub Releases.
'''
}

for filename, content in files.items():
    with open(os.path.join(docs_dir, filename), 'w', encoding='utf-8') as f:
        f.write(content.strip() + "\\n")

print("Filled all Documentation files with real content.")
