"""
=============================================================================
FILE: generator.py
PURPOSE: Part of the AAYU Intent-to-Silicon project
=============================================================================
This file is part of the AAYU (Aayu) Intent-to-Silicon Programming Language.
The AAYU language enables developers to write code using natural language
intentions, which are compiled to optimized backend code.

For beginners: This file handles part of the aayu intent-to-silicon project.
To understand the project architecture, see the ARCHITECTURE_FREEZE.md file.
=============================================================================
"""

import os
from generators.base import BaseGenerator

TYPE_MAP = {
    "text": "VARCHAR(255)",
    "number": "FLOAT",
    "integer": "INTEGER",
    "boolean": "BOOLEAN",
    "date": "DATE",
    "datetime": "TIMESTAMP",
    "uuid": "UUID",
    "email": "VARCHAR(255)"
}

class PostgresGenerator(BaseGenerator):
    def __init__(self, ir_data: dict, output_dir: str):
        super().__init__(ir_data, output_dir)
        self.sql_lines = []

    def _pluralize(self, word: str) -> str:
        # A very basic pluralizer for MVP
        if word.endswith("y"):
            return word[:-1] + "ies"
        elif word.endswith("s"):
            return word + "es"
        else:
            return word + "s"

    def generate(self):
        print(f"Generating PostgreSQL Schema in {self.output_dir}...")
        
        entities = self.ir.get("entities", [])
        relations = self.ir.get("relations", [])
        
        self.sql_lines.append("-- Generated by AAYU")
        self.sql_lines.append("-- Schema Version: 1.0\n")

        # Track which tables have foreign keys injected directly (one_to_many, one_to_one)
        # target_table -> list of SQL column definitions
        injected_fks = {}

        for rel in relations:
            source = rel.get("source", "").lower()
            target = rel.get("target", "").lower()
            rel_type = rel.get("type", "one_to_many")
            
            source_table = self._pluralize(source)
            target_table = self._pluralize(target)
            
            if rel_type == "one_to_many":
                col_def = f"{source}_id INTEGER REFERENCES {source_table}(id)"
                injected_fks.setdefault(target_table, []).append(col_def)
            elif rel_type == "one_to_one":
                col_def = f"{source}_id INTEGER UNIQUE REFERENCES {source_table}(id)"
                injected_fks.setdefault(target_table, []).append(col_def)

        # Generate Entity Tables
        for entity in entities:
            name = entity.get("name", "").lower()
            table_name = self._pluralize(name)
            fields = entity.get("fields", [])
            
            self.sql_lines.append(f"CREATE TABLE {table_name} (")
            self.sql_lines.append("    id SERIAL PRIMARY KEY" + ("," if fields or table_name in injected_fks else ""))
            
            # Fields
            for i, field in enumerate(fields):
                fname = field.get("name")
                
                # Skip if this field name is going to be injected as a foreign key
                # injected_fks contains strings like "doctor_id INTEGER REFERENCES doctors(id)"
                is_fk = False
                if table_name in injected_fks:
                    for fk in injected_fks[table_name]:
                        if fk.startswith(f"{fname} "):
                            is_fk = True
                            break
                if is_fk:
                    continue
                    
                ftype = TYPE_MAP.get(field.get("type", "text"), "VARCHAR(255)")
                
                # Check if this is the last item (either last field with no fks, or we have fks coming up)
                is_last_field = (i == len(fields) - 1)
                has_fks = (table_name in injected_fks)
                comma = "" if (is_last_field and not has_fks) else ","
                self.sql_lines.append(f"    {fname} {ftype}{comma}")
                
            # Injected Foreign Keys
            if table_name in injected_fks:
                fks = injected_fks[table_name]
                for i, fk in enumerate(fks):
                    is_last = (i == len(fks) - 1)
                    comma = "" if is_last else ","
                    self.sql_lines.append(f"    {fk}{comma}")
                    
            self.sql_lines.append(");\n")

        # Generate associative tables for many_to_many
        for rel in relations:
            source = rel.get("source", "").lower()
            target = rel.get("target", "").lower()
            rel_type = rel.get("type", "one_to_many")
            
            source_table = self._pluralize(source)
            target_table = self._pluralize(target)
            
            if rel_type == "many_to_many":
                assoc_table = f"{source}_{target}"
                self.sql_lines.append(f"CREATE TABLE {assoc_table} (")
                self.sql_lines.append(f"    {source}_id INTEGER REFERENCES {source_table}(id),")
                self.sql_lines.append(f"    {target}_id INTEGER REFERENCES {target_table}(id)")
                self.sql_lines.append(");\n")

        # Write to schema.sql
        self.write_file("schema.sql", "\n".join(self.sql_lines))

        print("PostgreSQL Schema generation complete.")
