from fastapi import FastAPI
from app.routers import router

app = FastAPI(title="${app_name} API", description="Generated by AAYU Intent-to-Silicon")

app.include_router(router)

@app.get("/")
def read_root():
    return {"message": "Welcome to ${app_name} API"}
