class AayuEmitter:
    def emit(self, architecture: dict) -> str:
        lines = []
        domain = architecture.get("domain", "App")
        
        lines.append(f"# ----------------------------------------------------")
        lines.append(f"# {domain} System - Auto-Generated by AAYU Intent Engine v4")
        lines.append(f"# ----------------------------------------------------\n")
        
        # 1. Entities
        lines.append("# 1. Entities")
        for ent in architecture.get("entities", []):
            lines.append(f"entity {ent}.")
            lines.append(f"    text name.")
            lines.append(f"end.\n")
            
        # 2. Relations
        lines.append("# 2. Relations")
        for rel in architecture.get("relations", []):
            rel_type = rel.get("type", "one_to_many")
            _from = rel.get("from")
            _to = rel.get("to")
            lines.append(f"relation {_from} {rel_type} {_to}.")
        lines.append("")
        
        # 3. Roles
        lines.append("# 3. Roles")
        for role in architecture.get("roles", []):
            lines.append(f"role {role}.")
        lines.append("")
        
        # 4. Workflows
        workflow = architecture.get("workflow", {})
        if workflow:
            lines.append("# 4. Workflows")
            wf_name = workflow.get("name")
            wf_entity = workflow.get("entity")
            lines.append(f"workflow {wf_name} for {wf_entity}.")
            for step in workflow.get("steps", []):
                lines.append(f"    step {step}.")
            lines.append(f"end.\n")
            
        # 5. CRUD Endpoints
        lines.append("# 5. CRUD Endpoints")
        for ent in architecture.get("entities", []):
            lines.append(f"crud {ent}.")
        lines.append("")
        
        # 6. UI DSL (Dashboard)
        lines.append("# 6. UI DSL")
        lines.append(f"page Dashboard.")
        lines.append(f"    heading \"{domain} System Dashboard\".")
        lines.append(f"    row.")
        for ent in architecture.get("entities", [])[:4]: # Max 4 cards
            lines.append(f"        card.")
            lines.append(f"            heading \"{ent}s\".")
            lines.append(f"        end.")
        lines.append(f"    end.")
        lines.append(f"end.\n")
        
        lines.append(f"task dashboardRoute with req.")
        lines.append(f"    map context.")
        lines.append(f"    return render \"Dashboard.html\" with context.")
        lines.append(f"end.\n")
        
        lines.append(f"get \"/dashboard\" to dashboardRoute.\n")
        
        # 7. Web Server
        lines.append("# 7. Web Server")
        lines.append(f"serve on 8080.\n")
        
        return "\n".join(lines)

if __name__ == "__main__":
    from intent_v4.architecture_builder import ArchitectureBuilder
    builder = ArchitectureBuilder()
    arch = builder.build("Build a Police Complaint System")
    emitter = AayuEmitter()
    code = emitter.emit(arch)
    print("\n--- Generated AAYU Code ---")
    print(code)
