import os
import sys
import json
import urllib.request
import urllib.error

def get_gemini_key():
    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        print("Error: GEMINI_API_KEY environment variable is not set.")
        print("Please set it before using the AI Builder.")
        sys.exit(1)
    return key

def call_gemini(prompt, system_instruction=None, json_mode=False):
    key = get_gemini_key()
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={key}"
    
    payload = {
        "contents": [{"parts": [{"text": prompt}]}]
    }
    
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }
        
    if json_mode:
        payload["generationConfig"] = {
            "responseMimeType": "application/json"
        }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    
    try:
        with urllib.request.urlopen(req) as response:
            res_body = response.read().decode("utf-8")
            res_json = json.loads(res_body)
            try:
                text = res_json["candidates"][0]["content"]["parts"][0]["text"]
                return text
            except (KeyError, IndexError):
                print("Error: Unexpected response format from Gemini.")
                return ""
    except urllib.error.HTTPError as e:
        print(f"HTTP Error {e.code}: {e.read().decode('utf-8')}")
        sys.exit(1)
    except Exception as e:
        print(f"Error calling Gemini: {e}")
        sys.exit(1)

def run_clarification_engine(intent):
    print("\n[1/5] Understanding intent...")
    
    system_prompt = """You are an expert software architect assisting in gathering requirements for an application.
The user has provided an initial idea. Your goal is to ask 2 to 4 clarifying questions about the architecture (e.g., users, auth, database, specific features) to ensure there is enough detail to build a data model and web routes.
DO NOT provide code. ONLY provide questions.
If the user's intent is already clear and no further questions are needed, or if they have answered your questions, reply with EXACTLY the string 'INTENT_LOCKED'.
Format your questions as a numbered list."""

    history = f"User's initial idea: {intent}\n"
    
    print("[2/5] Asking clarification questions...")
    
    while True:
        response = call_gemini(history, system_instruction=system_prompt)
        
        if "INTENT_LOCKED" in response.upper():
            print("\n[SUCCESS] Intent Locked!")
            break
            
        print("\nSystem: " + response)
        user_reply = input("\nYou: ")
        
        history += f"\nSystem: {response}\nUser: {user_reply}\n"
        
    return history

def generate_architecture(transcript):
    print("[3/5] Generating architecture...")
    
    system_prompt = """You are an expert software architect.
Based on the conversation transcript, generate a complete JSON architecture for the application.
The output MUST be valid JSON containing:
{
  "project_name": "string (PascalCase)",
  "entities": [ "string", "string" ],
  "routes": [ "/route1", "/route2" ],
  "auth": true/false,
  "database": "sqlite"
}
Output ONLY JSON. Do not include markdown formatting like ```json."""

    response = call_gemini(transcript, system_instruction=system_prompt, json_mode=True)
    
    try:
        # Strip markdown if present
        if response.startswith("```json"):
            response = response[7:]
        if response.endswith("```"):
            response = response[:-3]
        
        arch = json.loads(response.strip())
        
        with open("architecture.json", "w", encoding="utf-8") as f:
            json.dump(arch, f, indent=2)
            
        return arch
    except json.JSONDecodeError:
        print("Error: Gemini returned invalid JSON for architecture.")
        print("Raw response:", response)
        sys.exit(1)

def generate_aayu_project(arch):
    print("[4/5] Generating AAYU project...")
    
    project_name = arch.get("project_name", "GeneratedApp")
    entities = arch.get("entities", [])
    routes = arch.get("routes", [])
    has_auth = arch.get("auth", False)
    
    # 1. Generate main.aayu
    lines = []
    lines.append(f"# {project_name} - Generated by AAYU Intent-to-Silicon")
    lines.append("use http.")
    lines.append("use db.")
    
    if has_auth:
        lines.append("use auth.")
        
    lines.append("")
    
    # Generate Database Models
    if entities:
        for ent in entities:
            lines.append(f"entity {ent}.")
            lines.append("    text name.")
            lines.append("    text created_at.")
            lines.append("end.")
            lines.append("")
            
    # Generate Web Routes
    for route in routes:
        route_name = route.strip("/").replace("/", "_")
        if not route_name:
            route_name = "index"
            
        lines.append(f"task handle_{route_name} with req.")
        lines.append(f"    return render \"{route_name}.html\".")
        lines.append("end.")
        lines.append("")
        
        lines.append(f"route \"{route}\" to handle_{route_name}.")
        lines.append("")
        
    lines.append("serve on 8080.")
    
    with open("main.aayu", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        
    # 2. Generate Views
    os.makedirs("views", exist_ok=True)
    for route in routes:
        route_name = route.strip("/").replace("/", "_")
        if not route_name:
            route_name = "index"
            
        with open(f"views/{route_name}.html", "w", encoding="utf-8") as f:
            f.write(f"<html>\n<head><title>{project_name} - {route_name}</title></head>\n<body>\n")
            f.write(f"    <h1>{project_name}</h1>\n")
            f.write(f"    <h2>Page: {route}</h2>\n")
            if has_auth and route_name != "login":
                f.write("    <p><a href='/login'>Login</a></p>\n")
            f.write("</body>\n</html>")

def build_app(intent):
    transcript = run_clarification_engine(intent)
    arch = generate_architecture(transcript)
    generate_aayu_project(arch)
    
    print("[5/5] Compiling and Running...")
    import subprocess
    
    # Assuming cli.py is in the same directory or accessible via python cli.py
    cli_path = os.path.join(os.path.dirname(__file__), "cli.py")
    
    subprocess.run([sys.executable, cli_path, "compile", "main.aayu"])
    
    print("\nServer running: http://localhost:8080")
    print("Press Ctrl+C to stop.\n")
    
    try:
        subprocess.run([sys.executable, cli_path, "vm", "main.ayc"])
    except KeyboardInterrupt:
        print("\nServer stopped.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python ai_builder.py \"Build a CRM\"")
        sys.exit(1)
        
    build_app(sys.argv[1])
